"
" vim: set fdm=marker fcs=fold\:\ :
"
" vundle (plugins){{{
set nocompatible              " be iMproved, required for vundle
set noesckeys
filetype off                  " required for vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin() " {{{2
" let Vundle manage Vundle, required for vundle
Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
" Plugin 'vim-airline/vim-airline-themes'
"Plugin 'altercation/vim-colors-solarized'
Plugin 'cocopon/iceberg.vim'
Plugin 'vim-scripts/greenvision'

Plugin 'tpope/vim-commentary'    " gc adds comments
Plugin 'tpope/vim-fugitive'      " for git commands and branch in statusbar
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-repeat'        " enable repeat for supported plugins
Plugin 'tpope/vim-surround'      " ys,cs,ds - add,change,del surround
Plugin 'tpope/vim-unimpaired'    " pairs of handy bracket mappings
Plugin 'tpope/vim-vinegar'       " better use of netrw

Plugin 'airblade/vim-gitgutter'

Plugin 'vim-scripts/argtextobj.vim'  " provides a text object for function arguments
Plugin 'michaeljsmith/vim-indent-object' " provides a text object based on indentation level

Plugin 'w0rp/ale'                " syntax check

" Plugin 'edkolev/tmuxline.vim'    " for tmux status line
Plugin 'tmux-plugins/vim-tmux'   " syntax + more (shift+K for help e.g.)

Plugin 'ternjs/tern_for_vim'     " code-analysis engine for JavaScript
Plugin 'Valloric/YouCompleteMe'  " code-completion engine for Vim


Plugin 'docker/docker' , {'rtp': '/contrib/syntax/vim/'}

Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'wincent/command-t'

Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'

Plugin 'christoomey/vim-tmux-navigator'

Plugin 'akkerman/vim-jasmine'

Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'moll/vim-node'
Plugin 'mattn/emmet-vim'

Plugin 'mboughaba/i3config.vim'
Plugin 'godlygeek/tabular'

Plugin 'chr4/nginx.vim'

Plugin 'majutsushi/tagbar'

Plugin 'mileszs/ack.vim' " ack-grep

Plugin 'digitaltoad/vim-pug'

Plugin 'tmhedberg/SimpylFold' " Python folding
Plugin 'jmcantrell/vim-virtualenv'
Plugin 'vim-python/python-syntax'

" All of your Plugins must be added before the following line
call vundle#end()             " required for vundle }}}2

filetype plugin indent on     " required for vundle

" }}}
" various {{{

set history=200    " open with q:
set nowrap         " do NOT wrap long lines
set hidden         " when buffer modified and not in a window
set autowrite      " just write file to disk in a lot of cases
" set hlsearch       " highlight matching searches
set incsearch      " show first match while typing search
" tabs
set tabstop=4      " show existing tabs as 4 spaces
set shiftwidth=4   " indent 4 spaces with '>'
set expandtab      " insert 4 spaces when pressing tab
" hybrid linenumbers
set relativenumber
set number
" splits
set splitright
" tweaks for browsing
let g:netrw_banner = 1
let g:netrw_list_hide = netrw_gitignore#Hide()
let g:netrw_liststyle = 3 " treeview
" finding files # https://www.youtube.com/watch?v=XA2WjJbmmoM
set path+=**
set wildmenu
set wildmode=full
" visualize invisible characters
set list
set listchars=tab:»·,trail:·
" visualize max length
let &colorcolumn="79"
" join lines with comments
set formatoptions+=j

" mark lines longer than 90 chars as error
match ErrorMsg '\%>90v.\+'
" mark trailing whitespace as error
match ErrorMsg '\s\+$'

" }}}
" look and feel {{{

" colors
syntax enable
set background=dark


" statusline (vim-airline)
set laststatus=2   " always on

set mouse=a

set t_Co=256
colors iceberg

"}}}
" plugin related settings {{{

" airline {{{
let g:airline_powerline_fonts = 1
let g:airline#extensions#ale#enabled = 1
" }}}
" ale {{{
" let g:ale_sign_column_always = 1
let g:ale_sign_error = ''
let g:ale_sign_warning = ''
let g:ale_linters = { 'javascript': ['eslint']}

let g:ale_lint_on_text_changed = 1
let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
" let g:ale_set_loclist = 0
" let g:ale_set_quickfix = 1

nmap <silent> <F2> <Plug>(ale_next_wrap)
nmap <silent> <F3> <Plug>(ale_previous_wrap)
" }}}
" CommandT {{{
nmap <leader>l :CommandTBuffer<CR>
" }}}
" fugitive {{{
nmap <leader>gs :Gstatus<CR>
nmap <leader>gc :Gwrite <bar> Gcommit<CR>
nmap <leader>gg :GitGutterSignsToggle<CR>
"}}}
" mxw/vim-jsx {{{
let g:jsx_ext_required = 0
" }}}
" NERDTree Tagbar {{{
let NERDTreeIgnore=['node_modules', '__pycache__', '\.pyc$', 'env$[[dir]]']
nmap <leader>f :NERDTreeFind<CR><bar><c-w><c-p>
nmap <F7> :NERDTreeToggle<CR>
nmap <F8> :TagbarToggle<CR>
" }}}
" python-syntax {{{
let g:python_highlight_string_format=1
let g:python_highlight_string_formatting=1
" }}}
" Tern {{{
let g:tern_map_keys=1
" }}}
" UltiSnips {{{
" let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsSnippetsDir = '~/.vim/UltiSnips'
let g:UltiSnipsExpandTrigger = '<Tab>'
let g:UltiSnipsJumpForwardTrigger = '<Tab>'
let g:UltiSnipsJumpBackwardTrigger = '<S-Tab>'
" }}}
" youcompleteme {{{
let g:ycm_key_list_select_completion = ['<C-j>']
let g:ycm_key_list_previous_completion = ['<C-k>']
let g:ycm_key_list_accept_completion = ['<C-y>']
" }}}
" vim-markdown {{{
let g:markdown_fenced_languages = ["yaml", "java","sh", "javascript", "html", "abap"]
" }}}

"}}}
" automate stuff {{{

augroup newfile
    autocmd!
    autocmd BufNewFile Dockerfile    0r ~/.vim/template/Dockerfile
    autocmd BufNewFile Vagrantfile   0r ~/.vim/template/Vagrantfile
    autocmd BufNewFile *.html        0r ~/.vim/template/html
    autocmd BufNewFile .tern-project 0r ~/.vim/template/tern-project
    autocmd BufNewFile docker-compose*.yml 0r ~/.vim/template/docker-compose.yml
augroup END

augroup my_stuff
    autocmd!
    " edit vimrc
    autocmd bufwritepost $MYVIMRC source $MYVIMRC " source vimrc after saving
    nnoremap <leader>ev :vsplit $MYVIMRC<CR>
    nnoremap <leader>sv :source $MYVIMRC<CR>

    " Jasmine related
    autocmd BufReadPost,BufNewFile *.spec.js set filetype=javascript syntax=jasmine
augroup END


"}}}
" mappings {{{

" switch buffer by number
" nnoremap <leader>l :ls<cr>:b<space>
" switch off highlightsearch
nnoremap <leader>n :set hlsearch!<cr>
" format json
nnoremap <leader>j :%!jq '.'<cr>:set ft=json<cr>
" copy selection to clipboard
vnoremap <C-c> "+y

" }}}
" abbreviations {{{
iabbrev widht width
iabbrev lenght length
iabbrev heigth height
iabbrev eon energieonderbrekingen

" }}}
" Jasmine spec {{{

function! SpecAlternateFile(currentfile)
    let file = expand(a:currentfile)
    if match(file, ".spec.js$") >= 0
        return substitute(file, '\v^(.+).spec.js$', '\1.js', '')
    elseif match(file, '.js$') >= 0
        return substitute(file, '\v^(.+).js$', '\1.spec.js', '')
    else
        return a:currentfile
    endif

endfunction

function! SpecSwitch(currentfile)
    let altfile = SpecAlternateFile(a:currentfile)
    if bufexists(altfile)
        execute 'buffer ' . fnameescape(altfile)
    else
        execute 'edit ' . fnameescape(altfile)
    endif
endfunction

command! Spec :call SpecSwitch('%')

" normal mode mappings for jasmine
nnoremap <leader>jx mm[{Ix`m
nnoremap <leader>jjx mm2[{Ix`m
nnoremap <leader>jf mm[{If`m
nnoremap <leader>jjf mm2[{If`m
nnoremap <leader>je mm[{^x`m
nnoremap <leader>jje mm2[{^x`m

" }}}
