# ~/.tmuxinator/config.yml

name: config
root: ~/

windows:
  - editor:
      panes: 
        - vim .vim/vimrc .zshrc .tmux.conf .gitconfig
  - vimconfig:
      root: ~/.vim/
      panes: 
         - # zsh
